CREATE TABLE MEMBER_T (
    USERID VARCHAR2(20) PRIMARY KEY,
    USERPASSWORD VARCHAR2(20) NOT NULL,
    USERNAME VARCHAR2(20) NOT NULL,
    USEREMAIL VARCHAR2(50),
    USERPHONE VARCHAR2(20),
    JOINDATE DATE DEFAULT SYSDATE       
);

CREATE TABLE BOARD_T (
    B_ID NUMBER PRIMARY KEY,
    B_TITLE VARCHAR2(200) NOT NULL,
    USERID VARCHAR2(20),
    B_CONTENT VARCHAR2(2048) NOT NULL,
    B_CREATEDATE DATE DEFAULT SYSDATE,
    B_UPDATEDATE DATE DEFAULT SYSDATE,
    B_VIEWCNT NUMBER,
    B_LIKECNT NUMBER,
    FOREIGN KEY (USERID) REFERENCES MEMBER_T (USERID)
);

CREATE TABLE COMMENT_T (
    C_ID NUMBER PRIMARY KEY,
    USERID VARCHAR2(20),
    B_ID NUMBER,
    C_COMMENT VARCHAR2(1024) NOT NULL,
    C_CREATEDATE DATE DEFAULT SYSDATE,
    C_UPDATEDATE DATE DEFAULT SYSDATE,
    C_LIKECNT NUMBER,
    C_DISLIKECNT NUMBER,
    FOREIGN KEY (USERID) REFERENCES MEMBER_T (USERID),
    FOREIGN KEY (B_ID) REFERENCES BOARD_T (B_ID)
);

INSERT INTO MEMBER_T VALUES ('admin', 'admin', '이름', 'admin@admin.com', '010-1234-1234', SYSDATE);

commit;

drop table member_t;
drop table board_T;
drop table comment_t;

SELECT * FROM MEMBER_T;
