CREATE TABLE MEMBER_T (
    USERID VARCHAR2(20) PRIMARY KEY,
    USERPASSWORD VARCHAR2(20) NOT NULL,
    USERNAME VARCHAR2(20) NOT NULL,
    USEREMAIL VARCHAR2(50),
    USERPHONE VARCHAR2(20),
    JOINDATE DATE DEFAULT SYSDATE       
);

CREATE TABLE BOARD_T (
    NUM NUMBER(20) NOT NULL PRIMARY KEY,
    USERID VARCHAR2(15),
    TITLE VARCHAR2(75),
    PASSWD VARCHAR(12) NOT NULL,
    CREATEDATE TIMESTAMP NOT NULL,
    VIEWCNT NUMBER DEFAULT 0,
    REF NUMBER(20) NOT NULL,
    RE_STEP NUMBER(10) NOT NULL,
    RE_LEVEL NUMBER(10) NOT NULL,
    CONTENT VARCHAR(3000) NOT NULL,
    FILENAME VARCHAR2(500)
);

INSERT INTO MEMBER_T VALUES ('admin', 'admin', '이름', 'admin@admin.com', '010-1234-1234', SYSDATE);

commit;

drop table member_t;
drop table board_T;

SELECT * FROM MEMBER_T;
